import type { Note, Position } from './note.types';
import type { NotesState } from './notes-state.types';

export class NoteNotFoundError extends Error {
  readonly noteId: string;

  constructor(noteId: string) {
    super(`Note not found: ${noteId}`);
    this.name = 'NoteNotFoundError';
    this.noteId = noteId;
  }
}

/**
 * Options accepted by `createNote`. Every field is optional and overrides
 * the corresponding default. `id` is excluded because it is assigned by
 * the workspace's monotonic counter, not by the caller.
 */
export type CreateNoteOptions = Partial<Omit<Note, 'id'>>;

/**
 * Appends a new note to the workspace and increments the id counter.
 *
 * Defaults applied when the caller does not override them:
 * - `title`: `"Note {id}"`.
 * - `body`: `"This is note {id}."`.
 * - `position`: `{ x: 0, y: 0 }`.
 *
 * `position` is optional because the concept of an exact coordinate may
 * not apply in every presentation (notably mobile, where notes are not
 * placed on a floating surface). Following principle 2 of CLAUDE.md
 * ("the system supports more than it implements"), the model accepts a
 * fallback rather than forcing the consumer to invent a value that the
 * presentation will discard. The default of `{ x: 0, y: 0 }` is a
 * functional placeholder: consumers that care about position are
 * expected to compute and pass one explicitly.
 *
 * The id is generated by an incrementing counter stored in `state.nextId`
 * and assigned to the new note as a string. Each call increments the
 * counter so that ids remain unique within the workspace even after
 * notes are removed.
 */
export function createNote(state: NotesState, options: CreateNoteOptions = {}): NotesState {
  const id = String(state.nextId);
  const note: Note = {
    id,
    title: options.title ?? `Note ${id}`,
    body: options.body ?? `This is note ${id}.`,
    position: options.position ?? { x: 0, y: 0 },
  };
  return {
    ...state,
    notes: [...state.notes, note],
    nextId: state.nextId + 1,
  };
}

export function moveNote(state: NotesState, id: string, newPosition: Position): NotesState {
  let found = false;
  const notes = state.notes.map((note) => {
    if (note.id !== id) return note;
    found = true;
    return { ...note, position: newPosition };
  });
  if (!found) {
    throw new NoteNotFoundError(id);
  }
  return { ...state, notes };
}

export function focusNote(state: NotesState, id: string): NotesState {
  if (!state.notes.some((note) => note.id === id)) {
    throw new NoteNotFoundError(id);
  }
  const without = state.focusOrder.filter((entry) => entry !== id);
  return { ...state, focusOrder: [...without, id] };
}
